// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Empty: typeof import('./components/empty.vue')['default']
    MixListCell: typeof import('./components/mixListCell.vue')['default']
    MixLoading: typeof import('./components/mix-loading/mix-loading.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./components/share.vue')['default']
    UniLoadMore: typeof import('./components/uni-load-more/uni-load-more.vue')['default']
    UniNumberBox: typeof import('./components/uni-number-box.vue')['default']
    UploadImages: typeof import('./components/upload-images.vue')['default']
  }
}
